import test from 'node:test';import assert from 'node:assert/strict';import {databaseFixture} from './harness.mjs';import {setTestDatabase} from '../api/database.mjs';
process.env.NODE_ENV='development';process.env.DEV_SHOW_RESET='true';process.env.ENABLE_DEMO='true';
const {handleRequest}=await import('../api/handler.mjs');const {db}=await databaseFixture();setTestDatabase(db);const base='http://localhost:3000';
async function req(path,body,user,method){const r=await handleRequest(new Request(base+'/api'+path,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(user?{'Cookie':user.cookie,'X-CSRF-Token':user.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),{ip:'127.0.0.1'});const ct=r.headers.get('content-type');let data=ct?.includes('application/json')?await r.json():Buffer.from(await r.arrayBuffer());return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function register(email){const r=await req('/auth/register',{email,name:'Integration tester',password:'A safe test passphrase 1234'});assert.equal(r.status,200);return {cookie:r.cookie,csrf:r.data.csrf};}
await test('Authenticated API integration and secure workflows',async t=>{const a=await register('one@example.com'),b=await register('two@example.com');let bank,cash,person,obligation,tx,backup;
 await t.test('Netlify health route and legacy function path are served',async()=>{assert.equal((await req('/health')).data.status,'ok');const r=await handleRequest(new Request(base+'/.netlify/functions/api/health'),{ip:'127.0.0.1'});assert.equal(r.status,200);});
 await t.test('Unregistered requests and invalid CSRF are denied',async()=>{assert.equal((await req('/snapshot')).status,401);assert.equal((await req('/accounts',{name:'No'}, {...a,csrf:'bad'})).status,403);});
 await t.test('Create financial accounts and person',async()=>{bank=(await req('/accounts',{name:'Bank',type:'Bank',opening:'10000'},a)).data.id;cash=(await req('/accounts',{name:'Cash',type:'Cash'},a)).data.id;person=(await req('/people',{name:'Umar'},a)).data.id;assert.ok(bank&&cash&&person);});
 await t.test('API transfer is zero income and expense',async()=>{assert.equal((await req('/transactions',{type:'Transfer',amount:5000,account_id:bank,to_account_id:cash,description:'Withdraw cash'},a)).status,201);const s=(await req('/snapshot',undefined,a)).data;assert.equal(s.available,1000000);assert.equal(s.income,0);assert.equal(s.expense,0);});
 await t.test('Cross-tenant reads and mutations never expose records',async()=>{assert.equal((await req('/transactions',undefined,b)).data.total,0);assert.equal((await req('/transactions',{type:'Income',amount:1,account_id:bank,description:'Attack'},b)).status,404);assert.equal((await req('/snapshot',undefined,b)).data.accounts.length,0);});
 await t.test('Loan and partial settlement round-trip correctly',async()=>{tx=(await req('/transactions',{type:'Receivable',amount:2000,account_id:bank,funded:true,person_id:person,description:'Loan to Umar'},a)).data.id;obligation=(await req('/snapshot',undefined,a)).data.obligations[0].id;assert.equal((await req('/transactions',{type:'Received Payment',amount:500,obligation_id:obligation,account_id:bank,description:'Partial receipt'},a)).status,201);const s=(await req('/snapshot',undefined,a)).data;assert.equal(s.receivable,150000);assert.equal(s.available,850000);assert.equal(s.net,1000000);assert.equal((await req('/transactions',{type:'Received Payment',amount:1501,obligation_id:obligation,account_id:bank,description:'Too much'},a)).status,400);});
 await t.test('Local natural-language parser never posts without confirmation',async()=>{const before=(await req('/transactions',undefined,a)).data.total;const r=await req('/parse',{sentence:'Spent ₹250 on lunch using UPI today'},a);assert.equal(r.data.amount,250);assert.equal(r.data.category,'Food');assert.equal(r.data.type,'Expense');assert.equal(r.data.description,'lunch');assert.equal((await req('/parse',{sentence:'Received ₹500 from Umar'},a)).status,400);assert.equal((await req('/transactions',undefined,a)).data.total,before);});
 await t.test('Reconciliation accepts two-decimal balances and posts variance',async()=>{const r=await req('/reconcile',{account_id:cash,actual:'4999.99',reason:'Physical count'},a);assert.equal(r.status,200);assert.equal(r.data.difference,-1);});
 await t.test('Assistant queries actual stored receipts',async()=>{const r=await req('/assistant',{question:'How much did I receive from Umar?'},a);assert.equal(r.status,200);assert.match(r.data.answer,/500/);assert.match(r.data.mode,/Local/);});
 await t.test('What-if simulator leaves ledger unchanged',async()=>{const before=(await req('/snapshot',undefined,a)).data.available;const r=await req('/simulate',{type:'receipt',amount:500,obligation_id:obligation},a);assert.equal(r.status,200);assert.equal(r.data.available,before+50000);assert.equal((await req('/snapshot',undefined,a)).data.available,before);});
 await t.test('All export formats return real downloadable content',async()=>{for(const format of ['csv','xlsx','pdf']){const r=await req('/export?format='+format,undefined,a);assert.equal(r.status,200);assert.ok(r.data.length>20);if(format==='xlsx')assert.equal(r.data.slice(0,2).toString(),'PK');if(format==='pdf')assert.equal(r.data.slice(0,4).toString(),'%PDF');}});
 await t.test('Structured receivable report exports remaining amounts',async()=>{const r=await req('/export?format=csv&report=Receivable%20Report',undefined,a);assert.equal(r.status,200);assert.match(r.data.toString(),/remaining/);assert.match(r.data.toString(),/1500/);});
 await t.test('Analytics and report summary validate date ranges',async()=>{assert.equal((await req('/analytics?from=2026-01-01&to=2026-10-07&grain=monthly',undefined,a)).status,200);assert.equal((await req('/report-summary?from=invalid',undefined,a)).status,400);});
 await t.test('CSV import preview finds errors and duplicates',async()=>{const date=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});const rows=[{Date:date,Particulars:'Lunch',Expense:250},{Date:date,Particulars:'Lunch',Expense:250},{Date:'bad',Particulars:'Invalid',Income:10}];const r=await req('/import/preview',{account_id:bank,rows},a);assert.equal(r.data.valid,1);assert.equal(r.data.duplicates,1);assert.equal(r.data.errors,1);assert.equal((await req('/import/confirm',{rows:r.data.rows.filter(x=>!x.errors.length&&!x.duplicate).map(x=>x.transaction)},a)).status,200);});
 await t.test('Backup restore preserves relational balances in a new tenant',async()=>{backup=(await req('/backup',undefined,a)).data;const restored=await req('/restore',{backup},b);assert.equal(restored.status,200);const sa=(await req('/snapshot',undefined,a)).data,sb=(await req('/snapshot',undefined,b)).data;assert.equal(sa.available,sb.available);assert.equal(sa.net,sb.net);assert.equal(sa.receivable,sb.receivable);assert.notEqual(sa.accounts[0].id,sb.accounts[0].id);assert.equal((await req('/restore',{backup},b)).status,400);});
 await t.test('Password reset revokes sessions and changes password',async()=>{const r=await req('/auth/reset-request',{email:'one@example.com'});assert.ok(r.data.dev_token);assert.equal((await req('/auth/reset',{token:r.data.dev_token,password:'Another safe test passphrase 1234'})).status,200);assert.equal((await req('/snapshot',undefined,a)).status,401);assert.equal((await req('/auth/login',{email:'one@example.com',password:'Another safe test passphrase 1234'})).status,200);});
 await t.test('Logout cannot be triggered through a GET request',async()=>{assert.equal((await req('/auth/logout',undefined,b)).status,404);assert.equal((await req('/me',undefined,b)).status,200);assert.equal((await req('/auth/logout',{},b)).status,200);assert.equal((await req('/me',undefined,b)).status,401);});
}).finally(()=>db.close());
