import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import Papa from 'papaparse';
const safeText=v=>typeof v==='string'&&/^[=+@\t\r-]/.test(v)?"'"+v:v;
export async function importFile(bytes){
 const buffer=Buffer.from(bytes);if(buffer.length>2*1024*1024)throw Error('Import file must be at most 2 MB.');
 if(buffer.subarray(0,2).toString()!=='PK'){const out=Papa.parse(buffer.toString('utf8').replace(/^\uFEFF/,''),{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim()});if(out.errors.length)throw Error('CSV parse error: '+out.errors[0].message);if(out.data.length>10000)throw Error('Import at most 10,000 rows.');return out.data;}
 // Reject oversized ZIP expansions before the workbook parser allocates them.
 let expanded=0,entries=0;for(let p=0;p+46<buffer.length;p++){if(buffer.readUInt32LE(p)===0x02014b50){expanded+=buffer.readUInt32LE(p+24);entries++;if(expanded>20*1024*1024||entries>2000)throw Error('Workbook expands beyond the safe import limit.');p+=45+buffer.readUInt16LE(p+28)+buffer.readUInt16LE(p+30)+buffer.readUInt16LE(p+32);}}
 const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const sheet=wb.worksheets[0];if(!sheet)throw Error('No worksheet found.');if(sheet.rowCount>10001||sheet.columnCount>100)throw Error('Workbook exceeds the supported import size.');
 const cell=v=>{if(v==null)return '';if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='object'){if(v.formula||v.sharedFormula)return cell(v.result);if(v.richText)return v.richText.map(t=>t.text).join('');if(v.text)return v.text;return '';}return v;};
 const headers=sheet.getRow(1).values.slice(1).map(v=>String(cell(v)).trim()),rows=[];for(let i=2;i<=sheet.rowCount;i++){const values=sheet.getRow(i).values.slice(1);if(!values.some(v=>v!=null&&v!==''))continue;rows.push(Object.fromEntries(headers.map((h,j)=>[h,cell(values[j])])));}return rows;
}
export async function excelReport(report){
 const wb=new ExcelJS.Workbook();wb.creator='FINTRACK';wb.created=new Date();
 const s=wb.addWorksheet('Report',{views:[{state:'frozen',ySplit:1}]});const keys=Object.keys(report.rows[0]||{date:'',description:'',type:'',amount:0});const monetary=new Set(['amount','income_effect','expense_effect','cash_effect','original','settled','remaining','limit','used','target','saved']);s.columns=keys.map(k=>({header:k.replaceAll('_',' ')+(monetary.has(k)?' (INR)':''),key:k,width:k==='description'||k==='reason'?42:k==='id'?38:22}));
 for(const row of report.rows)s.addRow(Object.fromEntries(keys.map(k=>[k,['date','due_date'].includes(k)&&/^\d{4}-\d{2}-\d{2}$/.test(String(row[k]))?new Date(row[k]+'T00:00:00Z'):safeText(row[k]??'')])));
 s.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};s.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF162B45'}};s.getRow(1).height=26;
 s.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,s.rowCount),column:keys.length}};s.eachRow((r,i)=>{if(i>1){r.eachCell(c=>{if(c.value instanceof Date)c.numFmt='dd mmm yyyy';else if(typeof c.value==='number')c.numFmt=keys[c.col-1]==='percent'?'0"%"':'#,##0.00;[Red](#,##0.00)';});if(i%2===0)r.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF2F5F9'}};}r.alignment={vertical:'top',wrapText:true};});
 const sum=wb.addWorksheet('Financial position');sum.columns=[{header:'Measure',key:'label',width:38},{header:'INR / detail',key:'value',width:36}];sum.addRow({label:report.title,value:report.name});sum.addRow({label:'Period',value:report.from+' to '+report.to});for(const k of ['available','receivable','payable','cardLiability','net'])sum.addRow({label:k,value:report.snapshot[k]/100});for(const [k,v]of Object.entries(report.totals))sum.addRow({label:k,value:v/100});sum.getRow(1).font={bold:true};sum.getColumn(2).numFmt='#,##0.00';return Buffer.from(await wb.xlsx.writeBuffer());
}
export async function pdfReport(report){
 const doc=new PDFDocument({size:'A4',layout:'landscape',margin:36,info:{Title:'FINTRACK · '+report.title,Author:'FINTRACK'}}),chunks=[];const finished=new Promise((resolve,reject)=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);});
 const money=n=>'INR '+new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n/100);
 doc.fillColor('#162B45').font('Helvetica-Bold').fontSize(22).text('FINTRACK | '+report.title);doc.fillColor('#52667e').font('Helvetica').fontSize(11).text(report.name+' | '+report.from+' to '+report.to);doc.moveDown(1.2);
 const metrics=[['Available funds',report.snapshot.available],['Receivables',report.snapshot.receivable],['Payables',report.snapshot.payable],['Net position',report.snapshot.net]],top=doc.y;metrics.forEach(([label,v],i)=>{const x=36+i*193;doc.roundedRect(x,top,181,55,5).fill('#eef3f8');doc.fillColor('#52667e').font('Helvetica').fontSize(10).text(label,x+12,top+10,{width:160});doc.fillColor('#162B45').font('Helvetica-Bold').fontSize(14).text(money(v),x+12,top+29,{width:160});});doc.y=top+76;
 let keys=Object.keys(report.rows[0]||{date:'',type:'',description:'',amount:0});if(keys.includes('person')&&keys.includes('remaining'))keys=['person','reason','original','settled','remaining','due_date','status'];else if(keys.includes('limit'))keys=['name','period','category','limit','used','remaining','percent'];else keys=['date','type','description','category',/Income/.test(report.title)?'income_effect':/Expense/.test(report.title)?'expense_effect':'amount'];
 const available=doc.page.width-72,widths=keys.map(k=>k==='description'||k==='reason'?2.4:k==='date'||k==='due_date'?1.15:1),total=widths.reduce((s,n)=>s+n,0);for(let i=0;i<widths.length;i++)widths[i]=available*widths[i]/total;
 const header=()=>{let x=36,y=doc.y;doc.rect(36,y,available,28).fill('#162B45');keys.forEach((k,i)=>{doc.fillColor('white').font('Helvetica-Bold').fontSize(9).text(k.replaceAll('_',' ').toUpperCase(),x+7,y+8,{width:widths[i]-14,height:16});x+=widths[i];});doc.y=y+30;};header();
 for(let i=0;i<report.rows.length;i++){const r=report.rows[i],values=keys.map(k=>typeof r[k]==='number'?new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(r[k]):String(r[k]??''));doc.font('Helvetica').fontSize(10);const height=Math.max(30,...values.map((v,j)=>doc.heightOfString(v,{width:widths[j]-14})+14));if(doc.y+height>doc.page.height-62){doc.addPage();header();}const y=doc.y;if(i%2===0)doc.rect(36,y,available,height).fill('#f1f5f9');let x=36;values.forEach((v,j)=>{doc.fillColor('#253a54').font('Helvetica').fontSize(10).text(v,x+7,y+7,{width:widths[j]-14});x+=widths[j];});doc.y=y+height;}
 doc.y+=12;doc.fillColor('#52667e').font('Helvetica').fontSize(9).text('Amounts are INR. Derived from the posted financial ledger. Principal settlements and account transfers are not income or expense.',36,doc.y,{width:available});doc.end();return finished;
}
