CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,created_at TEXT NOT NULL,preferences TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),csrf TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS resets(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,type TEXT NOT NULL,currency TEXT NOT NULL DEFAULT 'INR',created_at TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS categories(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,subcategory TEXT NOT NULL DEFAULT '',color TEXT NOT NULL DEFAULT '#4574b5',UNIQUE(user_id,name,subcategory));
CREATE TABLE IF NOT EXISTS people(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,email TEXT,phone TEXT,notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),date TEXT NOT NULL,time TEXT NOT NULL DEFAULT '12:00',type TEXT NOT NULL,amount BIGINT NOT NULL CHECK(amount>0),category TEXT NOT NULL DEFAULT 'Other',subcategory TEXT NOT NULL DEFAULT '',description TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',method TEXT NOT NULL DEFAULT 'Bank',person_id TEXT REFERENCES people(id),tags TEXT NOT NULL DEFAULT '',recurring_id TEXT,obligation_id TEXT,reversal_of TEXT UNIQUE REFERENCES transactions(id),idempotency_key TEXT,created_at TEXT NOT NULL,UNIQUE(user_id,idempotency_key));
CREATE TABLE IF NOT EXISTS postings(id BIGSERIAL PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES transactions(id),user_id TEXT NOT NULL REFERENCES users(id),account_id TEXT REFERENCES accounts(id),book TEXT NOT NULL CHECK(book IN ('asset','liability','receivable','payable','income','expense','equity')),amount BIGINT NOT NULL,person_id TEXT REFERENCES people(id));
CREATE TABLE IF NOT EXISTS obligations(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL CHECK(kind IN ('receivable','payable')),person_id TEXT NOT NULL REFERENCES people(id),original BIGINT NOT NULL CHECK(original>0),reason TEXT NOT NULL,due_date TEXT,expected_date TEXT,created_date TEXT NOT NULL,origin_tx TEXT NOT NULL REFERENCES transactions(id),cancel_tx TEXT REFERENCES transactions(id),notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS settlements(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),obligation_id TEXT NOT NULL REFERENCES obligations(id),transaction_id TEXT NOT NULL UNIQUE REFERENCES transactions(id),amount BIGINT NOT NULL CHECK(amount>0));
CREATE TABLE IF NOT EXISTS budgets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,amount BIGINT NOT NULL CHECK(amount>0),category TEXT NOT NULL DEFAULT '',account_id TEXT REFERENCES accounts(id),period TEXT NOT NULL DEFAULT 'monthly' CHECK(period IN ('monthly','weekly')));
CREATE TABLE IF NOT EXISTS goals(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,target BIGINT NOT NULL CHECK(target>0),target_date TEXT,priority TEXT NOT NULL DEFAULT 'Medium',notes TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS contributions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),goal_id TEXT NOT NULL REFERENCES goals(id),transaction_id TEXT NOT NULL REFERENCES transactions(id),amount BIGINT NOT NULL CHECK(amount>0),date TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recurring(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('Income','Expense')),amount BIGINT NOT NULL CHECK(amount>0),account_id TEXT NOT NULL REFERENCES accounts(id),category TEXT NOT NULL,frequency TEXT NOT NULL,next_date TEXT NOT NULL,end_date TEXT,is_subscription INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,custom_days INTEGER NOT NULL DEFAULT 30);
CREATE TABLE IF NOT EXISTS recurring_events(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),recurring_id TEXT NOT NULL REFERENCES recurring(id),date TEXT NOT NULL,transaction_id TEXT NOT NULL REFERENCES transactions(id),UNIQUE(recurring_id,date));
CREATE TABLE IF NOT EXISTS attachments(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),transaction_id TEXT NOT NULL REFERENCES transactions(id),name TEXT NOT NULL,mime TEXT NOT NULL,content BYTEA NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reconciliations(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),account_id TEXT NOT NULL REFERENCES accounts(id),date TEXT NOT NULL,system_balance BIGINT NOT NULL,actual_balance BIGINT NOT NULL,reason TEXT NOT NULL,transaction_id TEXT REFERENCES transactions(id),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS closings(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),month TEXT NOT NULL,closed_at TEXT NOT NULL,UNIQUE(user_id,month));
CREATE TABLE IF NOT EXISTS notifications_read(user_id TEXT NOT NULL REFERENCES users(id),notification_key TEXT NOT NULL,PRIMARY KEY(user_id,notification_key));
CREATE TABLE IF NOT EXISTS audit(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,entity_id TEXT NOT NULL,detail TEXT NOT NULL,created_at TEXT NOT NULL,previous_hash TEXT NOT NULL,hash TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS transactions_user_date ON transactions(user_id,date,id);
CREATE INDEX IF NOT EXISTS postings_user_account ON postings(user_id,account_id);
CREATE INDEX IF NOT EXISTS obligations_user_due ON obligations(user_id,due_date);
CREATE INDEX IF NOT EXISTS audit_user ON audit(user_id,id);

CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,window_start BIGINT NOT NULL,requests INTEGER NOT NULL);
CREATE OR REPLACE FUNCTION fintrack_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Financial and audit records are immutable. Post a reversal instead.'; END; $$;
DROP TRIGGER IF EXISTS immutable_transactions_update ON transactions;
CREATE TRIGGER immutable_transactions_update BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_transactions_delete ON transactions;
CREATE TRIGGER immutable_transactions_delete BEFORE DELETE ON transactions FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_postings_update ON postings;
CREATE TRIGGER immutable_postings_update BEFORE UPDATE ON postings FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_postings_delete ON postings;
CREATE TRIGGER immutable_postings_delete BEFORE DELETE ON postings FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_settlements_update ON settlements;
CREATE TRIGGER immutable_settlements_update BEFORE UPDATE ON settlements FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_settlements_delete ON settlements;
CREATE TRIGGER immutable_settlements_delete BEFORE DELETE ON settlements FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_audit_update ON audit;
CREATE TRIGGER immutable_audit_update BEFORE UPDATE ON audit FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_audit_delete ON audit;
CREATE TRIGGER immutable_audit_delete BEFORE DELETE ON audit FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_obligations_update ON obligations;
CREATE TRIGGER immutable_obligations_update BEFORE UPDATE OF kind,person_id,original,reason,due_date,expected_date,created_date,origin_tx,notes,user_id ON obligations FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
DROP TRIGGER IF EXISTS immutable_obligations_delete ON obligations;
CREATE TRIGGER immutable_obligations_delete BEFORE DELETE ON obligations FOR EACH ROW EXECUTE FUNCTION fintrack_immutable();
INSERT INTO schema_versions(version) VALUES(1) ON CONFLICT DO NOTHING;
